### model
model_name_or_path: /root/autodl-tmp/DGM4_Project/training_models/base_models/Qwen3-VL-8B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
gradient_checkpointing: true
adapter_name_or_path: ../../outputs/qwen3-vl-8b/dgm4-curriculum/stage1-cls/checkpoint-3922

### dataset
dataset_dir: ../../datasets/dgm4_stage1_cls_v2
media_dir: /root/autodl-tmp/datasets
dataset: dgm4_stage1_cls_v2_train
eval_dataset: dgm4_stage1_cls_v2_val
template: qwen3_vl_nothink
default_system: "You are a multimodal forensic classifier. Determine whether the image-caption pair is REAL or FAKE, predict four atomic labels FS/FA/TS/TA as 0 or 1, and output the final category. Respond strictly in this six-line format: Verdict: [REAL or FAKE] FS: [0 or 1] FA: [0 or 1] TS: [0 or 1] TA: [0 or 1] Category: [category]"
cutoff_len: 2048
preprocessing_num_workers: 1
dataloader_num_workers: 8

### output
output_dir: ../../outputs/qwen3-vl-8b/dgm4-curriculum/stage1-cls-v2-chain
logging_dir: ../../logs/qwen3-vl-8b-dgm4-curriculum-stage1-cls-v2-chain
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 3
gradient_accumulation_steps: 3
learning_rate: 5.0e-5
num_train_epochs: 1.5
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
